#!/usr/bin/env bash

# Copyright 2017 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -euo pipefail

function guess_runfiles() {
    pushd ${BASH_SOURCE[0]}.runfiles > /dev/null 2>&1
    pwd
    popd > /dev/null 2>&1
}

RUNFILES="${PYTHON_RUNFILES:-$(guess_runfiles)}"

# Container_pusher only supports py2, which causes problems when the system
# default python is py3. This is a quick workaround to make sure that
# container_pusher is run using py2.
# We first find py2 from PATH. When found, we substitute the line
#     PYTHON_BINARY = 'python'
# with (assuming that the py2 found is located at /usr/bin/python2)
#     PYTHON_BINARY = '/usr/bin/python2'
# in the container_pusher launcher script, generated by bazel py_binary().
function find_py2_or_die() {
    # Search for python2. If found, return it.
    local py2_path="$(which python2)"
    if [[ "${py2_path}" != "" ]]; then
        echo "${py2_path}"
        return
    fi
    # Search for python version 2.
    for py_path in $(which -a python); do
        if ${py_path} -c \
            'import sys; sys.exit(0 if sys.version_info[0] == 2 else 1)'; then
            echo "${py_path}"
            return
        fi
    done
    echo "Python 2 not found in PATH." >&2
    exit 1
}

PY2_PATH="$(find_py2_or_die)"

sed "s|'python'|'${PY2_PATH}'|p" %{resolver} | \
    ${PY2_PATH} - \
    %{resolver_args} --template %{yaml} --image_chroot=%{image_chroot} %{images}
